### ISSUE TITLE
Enhancement request: BucketDimension

### ISSUE THREAD

**Issue by chrisgemignani** [juiceinc/recipe#37]
Create a BucketDimension that checks if values are between certain ranges and returns a value. This would be created by a list of value/condition pairs.

```
age_buckets:
   kind: BucketDimension
   buckets:
      - value: 'Newborns'
        condition: 
           field: age
           between: [0, 2]
      - value: 'Toddlers'
        condition: 
           field: age
           between: [3, 5]
      - value: 'Kids'
        condition: 
           field: age
           between: [6,12]
      - value: 'Teenagers'
        condition: 
           field: age
           between: [13,19]
...
```
