### ISSUE TITLE
Enhancement request: Support defining ingredients using other ingredients

### ISSUE THREAD

**Issue by chrisgemignani** [juiceinc/recipe#45]
yaml only. 

Field can refer to another Ingredient's field. 

For instance,
```
sales: 
   kind: Metric
   field: sales
   aggregation: sum
cnt_salespeople:
   kind: Metric
   field: salesperson_id
   aggregation: count_distinct
avg_sales:
   kind: DivideMetric:
   numerator_field: @sales
   denominator_field: @cnt_salespeople
```

would be equivalent to

```
avg_sales:
   kind: DivideMetric:
   numerator_field: 
        value: sales
        aggregation: sum
   denominator_field: 
        value: salesperson_id
        aggregation: count_distinct
```
