### ISSUE TITLE
Add between vector operator

### ISSUE THREAD

**Issue by chrisgemignani** [juiceinc/recipe#65]
Between is not supported in recipe or in ingredients.yaml.

We should support this in build_filter.

```
recipe.automatic_filters({
  age__between: [13,19])
```

Also we should be able to define conditions in ingredients.yaml that use `between` like this.

```
teenager_count:
   field: 
      value: person_id
      aggregation: count
      condition:
         field: age
         between: [13, 19]
```
