### ISSUE TITLE
Use labeled conditions for quickfilters

### ISSUE THREAD

**Issue by chrisgemignani** [juiceinc/recipe#66]
Once https://github.com/juiceinc/recipe/pull/63 is merged we can use labeled conditions to define quickfilters. This changes the quickfilter syntax from 

```
quickfilters:
- name: big values
  condition:
     field: foo
     gt: 20
- name: little values
  condition:
     field: foo
     lte: 20
```

to 

```
quickfilters:
- field: foo
  gt: 20
  label: big values
- field: foo
  lte: 20
  label: little values
```
